#!/usr/bin/env bash
#
# 설치 정합성 사전검사 검증 (FE-1047)
#
# 사고의 타입 에러 5건 중 4건은 코드 결함이 아니라 로컬 node_modules 가 대상 라인과
# 다른 것이었다(설치본 react 18.3.1 / 대상 라인 react ^19 + next 16). 사용자는 자기 코드가
# 5군데 깨졌다고 읽는다. 아무 스크립트도 이를 확인하지 않았다.
#
# 여기서 확인하는 것
#   ① 스큐를 첫 파괴적 변경(머지) 전에 잡고 불일치 목록을 보여주는가
#   ② 검사 위치 — develop 라인에서 시작해도 switch 후에 잡는가
#   ③ 오탐을 만들지 않는가 (판정 불가 항목은 차단하지 않는다)
#   ④ 두 락파일 형식(yarn 1 / Yarn Berry)을 모두 판정하는가  ← imsform 이식의 전제
#   ⑤ 기존 픽스처(yarn.lock 없음)가 회귀하지 않는가
#
# 사용법: bash scripts/test/staging-install-sync.sh
#
source "$(dirname "$0")/lib/harness.sh"
harness_init staging-install-sync

# yarn.lock + node_modules 를 만든다. 둘 다 untracked 이므로 커밋되지 않고, 브랜치를
# 옮겨도 남으며 --untracked-files=no 를 쓰는 워킹트리 검사에도 걸리지 않는다.
#   lock_v1 <락파일 버전> [설치본 버전]     설치본을 생략하면 node_modules 를 만들지 않는다
lock_v1() {
  printf '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n"left-pad@^1.0.0":\n  version "%s"\n  resolved "https://example.invalid/left-pad.tgz"\n' "$1" > yarn.lock
  _install "${2:-}"
}

# Yarn Berry(v2+) 형식 — descriptor 에 npm: 프로토콜, version 은 'version: X'
lock_berry() {
  cat > yarn.lock <<LOCK
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"left-pad@npm:^1.0.0":
  version: $1
  resolution: "left-pad@npm:$1"
  checksum: 10c0/deadbeef
  languageName: node
  linkType: hard
LOCK
  _install "${2:-}"
}

_install() {
  rm -rf node_modules
  [ -n "$1" ] || return 0
  mkdir -p node_modules/left-pad
  printf '{ "name": "left-pad", "version": "%s" }\n' "$1" > node_modules/left-pad/package.json
}

# <브랜치>의 package.json 에 의존성을 선언해 커밋·push 한다.
# push 까지 하는 이유: 미푸시로 남기면 FE-1045 의 ahead 가드가 먼저 차단해 정작 검사하려던
# 경로를 타지 못한다(하네스 함정 7번과 같은 종류).
declare_dep() {
  local BR="$1" RANGE="$2"
  git switch -q "${BR}"
  node -e '
    const fs = require("node:fs");
    const p = JSON.parse(fs.readFileSync("package.json", "utf8"));
    p.dependencies = { "left-pad": process.argv[1] };
    fs.writeFileSync("package.json", JSON.stringify(p, null, 2) + "\n");
  ' "${RANGE}"
  git add package.json; git commit -qm "chore: left-pad ${RANGE} 선언"
  git push -q origin "HEAD:${BR}"
  git fetch -q origin --prune
}

SKEW_MSG="설치본이 이 라인의 락파일과 다릅니다"

# ══ E1  스큐 → 차단 ══════════════════════════════════════════════════
case_hdr "E1  설치본 ≠ 락파일 → 차단 · 불일치 목록 · 머지·bump 미실행 · 원격 무변경"
fixture_staging e1
declare_dep staging/0.1 '^1.0.0'
lock_v1 1.3.0 1.0.0
git switch -q feature/FE-X
BASE="$(git rev-parse staging/0.1)"
REMOTE_BEFORE="$(remote_sha staging/0.1)"
run "bash scripts/merge-staging.sh feature/FE-X"
expect_blocked
expect_has "${SKEW_MSG}"
expect_has "락파일 1.3.0  ≠  설치본 1.0.0"
expect_has "yarn install"
[ "$(git rev-parse staging/0.1)" = "${BASE}" ]; ok "staging/0.1 무변경 (머지·bump 미실행)" $?
[ "$(git rev-list --count --merges "origin/staging/0.1..staging/0.1")" -eq 0 ]; ok "머지 미실행" $?
expect_ver 0.1.0
[ "$(remote_sha staging/0.1)" = "${REMOTE_BEFORE}" ]; ok "원격 staging/0.1 무변경" $?
expect_clean_tree
head_is staging/0.1                              # yarn install 이 이 라인 기준으로 돌아야 한다

# ══ E2 · E4  일치 → 통과, 문구 미출력 ════════════════════════════════
case_hdr "E2  설치본 == 락파일 → 통과 (정상 플로우 회귀)"
fixture_staging e2
declare_dep staging/0.1 '^1.0.0'
lock_v1 1.3.0 1.3.0
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_success
expect_ver 0.1.1
head_is feature/FE-X

case_hdr "E4  일치 상태에서 가드 문구 미출력 (부재 단언)"
# E2 의 출력을 그대로 재검사한다
expect_absent "${SKEW_MSG}"
expect_absent "node_modules 가 없습니다"
expect_absent "yarn install"
expect_absent "판정하지 않은 선언"

# ══ E3  node_modules 없음 ════════════════════════════════════════════
case_hdr "E3  node_modules 자체가 없음 → 차단 + 안내 (크래시 아님)"
fixture_staging e3
declare_dep staging/0.1 '^1.0.0'
lock_v1 1.3.0                                    # 설치본 없음
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_blocked
expect_has "node_modules 가 없습니다"
expect_has "yarn install"
expect_absent "TypeError"                        # 부재 단언 — 크래시가 아니다
expect_absent "ENOENT"
expect_absent "Cannot read"
expect_ver 0.1.0

# ══ E5  라인 의존성 격차 → 정보성, 차단 아님 ═════════════════════════
case_hdr "E5  develop 과 의존성 선언이 다름 → 정보성 한 줄, 차단 아님"
fixture_staging e5
declare_dep develop     '^0.9.0'
declare_dep staging/0.1 '^1.0.0'
lock_v1 1.3.0 1.3.0                              # 설치는 일치 → 차단 대상 아님
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_success                                   # ★ 차단하지 않는다
expect_has "이 라인은 develop 과 의존성 선언이 다릅니다"
expect_has "left-pad ^0.9.0 → ^1.0.0"
expect_absent "${SKEW_MSG}"                      # 부재 단언 — 격차는 스큐가 아니다
expect_ver 0.1.1

# ══ E6  검사 위치 ════════════════════════════════════════════════════
case_hdr "E6  검사 위치 — develop 라인에서 시작해도 switch 후 스큐를 잡는다"
fixture_staging e6
declare_dep staging/0.1 '^1.0.0'
lock_v1 1.3.0 1.0.0
git switch -q feature/FE-X
# 작업 브랜치(develop 라인)에서 직접 돌리면 통과한다 — 그 시점 package.json 에는 선언이
# 없어 비교 대상이 없다. 그래서 switch '전' 에 두면 이번 사고를 못 잡는다.
run "node scripts/check-install-sync.mjs"
expect_success
expect_absent "${SKEW_MSG}"
# 같은 상태에서 staging:merge 는 switch 후 검사가 돌아 잡는다
run "bash scripts/merge-staging.sh feature/FE-X"
expect_blocked
expect_has "${SKEW_MSG}"

# ══ E7  오탐 방지 ════════════════════════════════════════════════════
case_hdr "E7  락파일에서 못 찾은 선언은 판정하지 않는다 (오탐 = 배포 차단)"
fixture_staging e7
declare_dep staging/0.1 '^2.0.0'                 # 락파일 descriptor 는 ^1.0.0 → 매칭 안 됨
lock_v1 1.3.0 1.0.0                              # 설치본이 달라도 판정 대상이 아니다
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_success                                   # ★ 차단하지 않는다
expect_absent "${SKEW_MSG}"                      # 부재 단언
expect_has "판정하지 않은 선언 1건"                 # 판정하지 않았다는 사실은 알린다
expect_ver 0.1.1

# ══ E8  Yarn Berry 형식 ══════════════════════════════════════════════
case_hdr "E8  Yarn Berry 형식 락파일도 판정한다 (imsform 이식의 전제)"
fixture_staging e8
declare_dep staging/0.1 '^1.0.0'
lock_berry 1.3.0 1.0.0
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_blocked
expect_has "${SKEW_MSG}"
expect_has "락파일 1.3.0  ≠  설치본 1.0.0"
expect_absent "판정하지 않은 선언"                  # 부재 단언 — descriptor 를 실제로 찾았다

case_hdr "E8b Berry 형식 + 일치 → 통과"
fixture_staging e8b
declare_dep staging/0.1 '^1.0.0'
lock_berry 1.3.0 1.3.0
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_success
expect_absent "${SKEW_MSG}"
expect_ver 0.1.1

# ══ E9  검사 대상 아님 → 조용히 통과 ═════════════════════════════════
case_hdr "E9  yarn.lock 없음 → 조용히 통과 (기존 298건이 이 조건이다)"
fixture_staging e9
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_success
expect_absent "${SKEW_MSG}"
expect_absent "node_modules 가 없습니다"
expect_absent "판정하지 않은 선언"
expect_ver 0.1.1

case_hdr "E9b PnP(.pnp.cjs) → 조용히 통과 (node_modules 비교 대상 아님)"
fixture_staging e9b
declare_dep staging/0.1 '^1.0.0'
lock_v1 1.3.0                                    # node_modules 없음 = PnP 상태
: > .pnp.cjs
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_success
expect_absent "node_modules 가 없습니다"           # 부재 단언
expect_ver 0.1.1

# ══ E10  하드 제약 ═══════════════════════════════════════════════════
case_hdr "E10 check-install-sync.mjs 는 yarn 을 호출하지 않는다 (픽스처 제약)"
# 픽스처에는 yarn 도 .yarnrc.yml 의 yarnPath 도 없다. yarn 을 부르면 전 케이스가 깨진다.
! grep -qE "(execFileSync|execSync|spawnSync|spawn|exec)\(\s*['\"]yarn" "${SRC}/scripts/check-install-sync.mjs"
ok "yarn 호출 없음" $?
[ "$(grep -cE "execFileSync\(\s*'git'" "${SRC}/scripts/check-install-sync.mjs")" -eq 1 ]
ok "외부 명령은 git show 하나뿐 (읽기 전용)" $?

# ══ E11·E12  이식 과도기 — 라인에 검사기가 아직 없거나 고장난 경우 ══════
# 실측(2026-09): 이식 커밋은 feature 브랜치에만 있는데 merge-staging.sh 는 실행 도중
# staging 라인으로 switch 한다. 그 라인에 이 파일이 없으면 MODULE_NOT_FOUND(exit 1)로 죽고,
# 호출부가 그것을 '설치 스큐' 로 오인해 잘못된 안내를 냈다.
# 차단은 답이 아니다 — 이 파일을 추가하는 이식 머지 자체가 영원히 막힌다(닭-달걀).

case_hdr "E11 staging 라인에 검사기가 없음 → 안내 후 계속 (머지·배포 성공)"
fixture_staging e11
git switch -q staging/0.1
git rm -q scripts/check-install-sync.mjs
git commit -qm "chore: 검사기가 아직 없는 라인"
git push -q origin staging/0.1
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_success                                   # 데드락 금지
expect_has "설치 정합성 검사가 아직 없습니다"      # 무음 금지
expect_absent "Cannot find module"               # 크래시가 새어 나오지 않는다
expect_ver 0.1.1
head_is feature/FE-X

case_hdr "E12 검사기 자체가 고장 → 스큐와 다른 안내로 차단 (exit 2 분기)"
fixture_staging e12
git switch -q staging/0.1
printf 'throw new Error("boom");\n' > scripts/check-install-sync.mjs
git commit -qam "chore: 고장난 검사기"
git push -q origin staging/0.1
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_blocked
expect_has "설치 상태 문제가 아닙니다"             # 호출부가 낸 '검사기 실패' 안내
expect_has "yarn install 로는 해결되지 않습니다"
expect_absent "설치를 맞춘 뒤"                    # 스큐 안내로 오인하지 않는다
expect_ver 0.1.0                                 # bump 미실행

# 검사기가 통째로 깨진 경우(E12)는 node 가 exit 1 로 끝내므로 호출부 메시지만 나온다.
# 검사기가 살아 있고 내부에서 예외를 만난 경우는 스스로 exit 2 로 끝내며 자기 메시지를 낸다.
case_hdr "E12b 검사기가 내부 예외로 실패 → exit 2, 스큐와 다른 안내로 차단"
fixture_staging e12b
declare_dep staging/0.1 '^1.0.0'
lock_v1 1.3.0 1.3.0                              # node_modules 까지 만든다(스큐 없음)
rm -f yarn.lock && mkdir yarn.lock               # 읽으면 EISDIR — 검사기 내부에서 예외
git switch -q feature/FE-X
run "bash scripts/merge-staging.sh feature/FE-X"
expect_blocked
expect_has "검사기 자체가 실패했습니다"            # 검사기가 스스로 낸 메시지 (exit 2)
expect_has "yarn install 로는 해결되지 않습니다"
expect_absent "설치를 맞춘 뒤"
expect_ver 0.1.0

harness_summary
